build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - run python manage.py test

publish:
    docker:
        repo: $$DOCKER_USERNAME/ahod_server2
        tag: latest
        username: $$DOCKER_USERNAME
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        when:
            branch: "master"

    docker:
        repo: $$DOCKER_USERNAME/ahod_server2
        tag: dev
        username: $$DOCKER_USERNAME
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        when:
            branch: "dev"

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: $$MANTL_USERNAME
            password: $$MANTL_PASSWORD
        urls:
            - https://$$MANTL_CONTROL/marathon/v2/apps/imapex/ahod/ahod-server2/restart?force=true
        when:
            branch: "master"

    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: $$MANTL_USERNAME
            password: $$MANTL_PASSWORD
        urls:
            - https://$$MANTL_CONTROL/marathon/v2/apps/imapex/ahod/ahod-server2-dev/restart?force=true
        when:
            branch: "dev"